version: 2

project_name: jevons

builds:
  - id: jevons
    main: ./cmd/jevons
    binary: jevons
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^test:"

brews:
  - name: jevons
    repository:
      owner: giannimassi
      name: homebrew-jevons
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/giannimassi/jevons"
    description: "Local AI usage monitor and dashboard"
    test: |
      system "#{bin}/jevons", "doctor"
    install: |
      bin.install "jevons"
